CREATE USER c##dma6m6
  IDENTIFIED BY 12345678
  DEFAULT TABLESPACE USers
  QUOTA UNLIMITED ON users
;

GRANT CREATE SESSION TO c##dma6m6;
GRANT CREATE TABLE TO c##dma6m6;
GRANT CREATE VIEW TO c##dma6m6;
GRANT CREATE SEQUENCE TO c##dma6m6;
GRANT CREATE PROCEDURE TO c##dma6m6;
GRANT CREATE TYPE TO c##dma6m6;
GRANT CREATE TRIGGER to c##dma6m6;
